---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: citroen-postgres-credentials
  namespace: citroen
spec:
  encryptedData:
    password: AgBphMQsipnh/IpLXhC2TPR/SJ1ni6DcmeKV307HzZSpK00QOMnlMXMVPm0QBM0o0A59B9k3j1XUfgL7xgf0YT9cb/yCnLYPMx6xIwUgXtwXuB6NK8sEBPcCamB6haGI8DGXDkauPW1PzR22X2qDtpdJsRW2fdc842+Tmb5XXqit5DvnjSkyAnG8shPfZUhqawVyIpmC9xUCYe8jEumvHM87rofI4Jj0LHfNPzEbYqhiyfprE76wEk4E2j4YypKX5wQ5a6QoXEwNCUtAsekxUk93mgpKUxwU4ybWpheuLyfxzL/9WHpaAh55obodEhYvWP/PK5wrIDG80/0ys6/GFCrKNChWXWdyTJvy5vBXRwBgg7k0DkdCoBUTYl0hBgPzShIJpY10353ertnkgKpB8vTIOg4QhiiveWk4jU4FHKjjbIVJ8ebGclrUt1JvZd1jSWJBlD0KwtvfIxeW7GZkOjksKXFabOIMWSelH4E5Y9T8gUzMZ6bLUwpclTwazdptIA6NHo85aF3DTsdoZZMN9YfX5SU+P46zEvsfjtcyLuitObzc0+IoVrXfyQk5QHoxH7g0rttMq7/4cCr4b46pxzjs5WJ/HP4rK2x6tayKt92MYJSTa+gmf/jODEfG1PIHIgT4SoKy8/0EZRKKrHq47X49M8kuv4XPcRIS6x84APnSOozH0DVk8g4C/zbD3J7+04R4kmp/mFosIvDjv/LOreecNQrsIhmgUxvw+9zX+He47w==
    username: AgAogCLiCpxgjwt4OxbFPTH+NiAkvDyJgcoDTTaGnhWg/eNKqvKapojj+9a4T2go8Y8i17hDyqXYNzloV4irkCF02bu7PauV8fnb1ujrpA+50sI7fw5OU79RteY6CKklBnfj6uhmhTGxzGq1BWJliHa07lH8+YMI0z9wI/QLSlO5s8LKcUFFpQh4QKNRF+ANOyTiKzpXAuFuyQwSkZp7fVTPWyIT03cIAj1phvJbgcilbz8s8M88ChbkvejkPDxK72AKUPCjk91Ah0n/HWWrWVV1PzaWFNMDCe+VK1q7MNRPYRoDe6Z257HA4dfNS+87l4CwnpfAE/EbgZsjU7DNYZl5IIwYxVo6KJg/kue0ow0V/g4uZtNtpfnHjSP5mMFvxNj0lfS8CFfmveh+hxuv5ozUId9zaurqMYxvM9Pd6woz6pUwbTMvmiKKQLc6q+DhtI1NcvOhoB3TuA+6se78a22USMscW62U408p1UGFlsGuw4hI5sQTO4KtB/WMK5tScsBbUxwW0rNzjKc3RkQ/dGVKu7I3iope45TaUwHu+K9vDaP7gullvNtdXytS0lY0cB4CCJ9nULGrb4s5U7QJCAoO4LmJjj0VQXfveVEGef0qlURtsPLmVCjCgpr+OpszGpQIpf9nSasAV3rKkgDxbIXAi1i5099MykyiCXZxhihUaWwzXU8zoj/89XPYtYWxOVPj+Gc=
  template:
    metadata:
      name: citroen-postgres-credentials
      namespace: citroen
    type: kubernetes.io/basic-auth
