---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: citroen-grafana-reader
  namespace: citroen
spec:
  encryptedData:
    password: AgBODDJPLv0/iczNF23OkIJ/gY19++XOcAlSxzWx9Bl15Nk/nR/Ju6GANfw7Rn7XdJKn+vg27vssQC/CsSBKEwSW8c3Q9jIGwkT6q1MCJ5OJPu/0bHvt2kG5RJKfN/T3bWaLFSGNdfx5geqelDN84fE4YKqkNZDMukxJYd8Oc+n0gfw6FzwEpXgA4ddI2HwSnMsu1cjbUmOZk3o0/XZI2knwFHahfc8CvUVOWfm6xI5Tc+iTa6/jpSEsMP+6/ZAx1oHhJ3ZBtXzVJiDf+GZPK1jp9DGXf6Rk/FI0KiJ+Cq/9yLFTlITDjMBuWjsSfYB+6FYMH0K5GrkiMQ/+5Ru8zekk0Eta6W1jgq+y0nMI99H2nMvo5KdPdJOlIRqSmny1/6Imt9X2JmLRQn5avH+RM0PreIPC0E56UZ90zQgwuaxCbCd2KS8sQQmtT7x5ITJ3+dZ0n8ZvqI2MJcgE0F/6hPHLPKQ45UwNWIdmHgi6fO4k0R6t5MOsh4ciZJfFro6M07UB9PEsXwdk7XpKKxIjIhynexSjhmX9O4Ff7KeLRfR06a+gh4AIkNUo6ig0xG/hGqEnNk9Bcx5LAY/qRBE1YVwnomf7cYv/bCBU1Nn9x7XlGKRyVgQfDAcvgXWnXjruDx+0DYAcdNO8rCUYCWieoApHnWhzJ89CHcQyRQ14x13qteh7qTTiIAHM37z8Y78nSqW4HzCVU/ijnbSACU2ShgzC2wg9Sy53mDHDiqKPorgQDG0OsDG/IzTW1YuRS906aTk=
    username: AgBY7W9lMWbQHe4tlo0lKY7BJoWPLoePVjXk8R8xJ0z1tfhxf2rBQujZLr1yzUhqVxetxy+e7lXnRoVBvUBB3PjYQsGbAU8nTOKia+pP/YnXTRU3XV+Vi2JaozdigMM8yY9l7FMybRw5+bnq7ukpDYmuEJQKxqi21ZlqnLJ9f4bK77mfV0C20rck6aF37MlIT+8M05NYgumsMX5hk7OmpleOOmO+AiLmD5kQAt857QhQrxb05OufT+ORgzsIh4BqvyOCmrBkvalYQpgjFjr8J0ohps9B9jDd7QLqKKrwgOjeOaq0HUF2J85mn1BOWRG/NkSK0zvFLhy9qlN7JxfcAk5/+/8XHAgAwZJf++2mLxEzuf0QGrJYu0+zCpE9IXGBWI6Mwwsta266M6cuYQ/dd2HwqaUCJcdT1WyysraXwDmYByLKcyF1nXspLBhriV8mcCzJOfL793VHajjF7Tyow+soMo5MzF0Xd5vzRf546HIb8+cUQvmu5IPPbS5CXh05zMGkR5IZ1vklal48KWhVfGLOF51CXDPF3PgXuQHnlkFqQHfJoDCWoP6Xm33YvrWJmuP8girMHebekEWrmfiEXZ2snL/lgE3xyGIAZBOLymprJF37Oie7PiB4I/1rjsZbs2TF89glQPVKkP2prh0lTdwUgqZfUqHVlIEq4RCaqwOohdxnEqxeXtzr8UcQVp4pFNlbmY7qaHk0oWCw5YYCMg==
  template:
    metadata:
      name: citroen-grafana-reader
      namespace: citroen
    type: kubernetes.io/basic-auth
