apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartctl-exporter
  namespace: monitoring
  labels:
    app: smartctl-exporter
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: smartctl-exporter
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 30s
