apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-datasource-postgres
  namespace: monitoring
spec:
  encryptedData:
    password: AgA+x6Ll8IfgEbxE6avSIYmyJakIFno3hEKX3xX/bA+PdwpXmzYXoBm33LFq5xZALsSco0EXMJvOMLixIFMi1UKqfQu+9cO2TsY7ly7Jw40+nOTo25B9l135MeG9UwMxZNO2FtsBMJz8sUQDzhaYrb0VTHZgvYnqvh8tLFQNORHiB/DZHP2xGPTYVEbQDZPRaFY919Nkn1lSurVwk3uq676lKWua1g0hKe0Ahyicg5sjlupsj4xiL/jWIOHCAVf2DjyK/wxmsQP3J9vZM4omFaSDgIOnJiUb8Qqzt5kDy3bp1GT53p3SXhx4iYWyLD2xbTxEkKhohicNMTyckojsYedM9NaOZsM/6O97AJxBY7NsYMI9P8eVR1wm9sWiTItNuk5Y/fmQ2ZKvmtWeiPaKcVaACMYJI7BvUSf8OlPdh286mObK6tDzakqGUMTLfV+NqaxOgJYCc8plfCrW97j2ce8wbSF0ueEypuacqAFdfRyfaKzzQ+IN+hwCcdQFDT656PiDQA25Gjf7EJai5dO5c3WCtOO9ELKiByWDfltr9dODL884xQ9kokPs6kM/SBPCSzwwyHxhMsPh2lxdwRShg77/7AME+e995CMwLdwgwnATatkEb5gHepZvWKQc19VHcYWOLZ++Dbug4IBkxWmOAA73WuDfgP87JEaMn8IewcNP66D1W/g8tzd4Qug5gZ9HN1PYortRZRYA0tC3R8pjNK9fYR49axZhkb2dtlyZ24lDyi7E20Wt+KawzwhZIzU3jRU=
  template:
    metadata:
      name: grafana-datasource-postgres
      namespace: monitoring
    type: Opaque
