apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
  namespace: monitoring
spec:
  instances: 2
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  postgresql:
    parameters:
      max_connections: "100"
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
