apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sish-data
  namespace: sish
  labels:
    app.kubernetes.io/name: sish
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
