---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgCp28owrIjvG1zke1zFymedpXRCpMEUjdfTZLIRYu3YbFG+wArJ/2jnA0CCy1sflHlfHnISzdga2Au1ju5Iyr4d/BXcI72YaCQGr7G2ZxTWV+2flxTY2Z1nj7PYnan2exBz5PX/SobPmTpgbzjLDXnjJi5GXi/Ik2jEDHnfc8n3eUHRuzJqV1wYRVBIEHDFYY04lf/6A30JvBJMXRa9op4ovW4pOzbmJ7pWDgiPm/a301TEGA4Gv90jW193Ew3bPkciTq31zeOsvxb9sf1e7FJ/YutsKW36YEB9JIJNDs7+BLHd+dGLLV/WKpprmJpI8oK+JLpFbrqHyOlbAhJ6hJDgS27Of3S4YPVTEL2JSuOHjuAo2h/Z3yMrqRNVYOJ7ewSFv0K2IkErt9ZqfGclIDy8csT1ocRmF02o3DBnNPrBKMCb4ihydGRZ4OF95chvdTIhwuSTYHFlEkUJr61W3EkVfcxWAjHRvhk43JrJANBWiQYqk0fMuaqi2bnENZ62RIKqbWlHFoeCqlw3y5qouMC05PCwWvuiPPmc2DFGEfgHYz1hrZwtjlCBWQy5yWgpszevfEwysJsafEHUMCM4cLsCIQJCwdfI5UR9hm3hxv1qv8/nnQ+2WanbTu4f3lEbl6t3DeQV3Ufg0lazAxoH/TbycbIoD2MbF4foFS1ziMfkqHYQZMR01Ix3UaOw4vw1+S8MYMzQvcZZnW/5B4mZzPQ1NrK3DTiYnyDAHJ5novXBg2yKGMUYJLKpNiO+7g==
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
