---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgCu0i5CLthTSo+J6ASUkQVMjNatsdPrVr/ykqeJ0GVVPAfSOTyGIsfFq/LZKFPId4FntbZKHqOr4FIstfqUU+1WvaAhm5eizYlz9S4cY1dJG1tHS4CIiq29r3Tqx5ZLbtEjLVXuWP+7t39S3nPVc4pB3KUOHS3K3ZTzyTvIMLBb+2jDbe5acG6P7ckLGCJ9krmYNdBOVcrNULnQMEXjKpSv6Q/DmfrwTRohM45dFvvxpZC/a5BZf/x3nQoqvm0GHODDJICcEGmbBEHGWAE++vIhjlPHldOpCyFfVV22FeykxHBJzCr+nqETL5LjGCKbgD5XCrNvEjkD1CaAWDmFWkHJmIv5QpWsm3EfzTsrkEe7DKXWrcYeSxqOJAY23Fry+C1Cb+c5571yRRpQLEGBUeL5YTdrfXujHYB8IdFve7FMzV8SOwDaoQN8yvFlFWdqmfETLV7lF9Ev+f4vw+qyhbujb0KCsTdRSVZwSdVFw9yFooJp9sG7qCsFQXVNckxG48YZgxgl5bNXWGAeeOzcEpcVAteR9h8A2U2C5FFG/B4uyIimbWRiANfDu2QoR5f7zlmgv6p9TUuHlE2x+D5mV9e6QxLniJ9wZyWE8NnqYIcw8j1ujsPiYLorNPpC8j9ilIrQfcdEf2mQzmi9meSM0H1vdeEOTDcNPek/ESvVvHwL/vUg+tzV5cAOg4bL78rMkzhq5YPQJLKu1rSqzzJqCfkpJrqVWZOw96OwX79TBeM6NOTgjX/zEjxn77ye5X1p
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
