---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgAadstWa+C25p22FrKl3sr6GcAhvpHqS2wEbTg+sa/XqDQ0pCsZjIkNM4ckpxshy6/qqUE61J6+7LtRJ0A+PEa9xmb8BtqBFltEG1NzpRYdlYOHRM1ST8Eb9RM9BVP7ZlzyJFEdx87dXFIFkA0/tVxJoDbD3pGwAInVlOpl5i0RBjPkqiL/5VRkrNzP19ebQOpT7rK97+SsgnQ+jW4cx8rJgzWfMul3Tl3rT4f6cJSzWOLh2Bjt0/pITlElysAI8bBE//9Nq5Xq/m4Ak+ESJbhOgEU7xQg5TDr4OV9/3O0vaAGaM7BjJYcAchERxXxdrYrV9jew1vSiqJCqMKJcnn1TU9THyqHrhaRVJFAQ+PRfNl7RxWrSFw+rualZlJvKDf9IS3UN7ozUSsA4r97ZTu3yVCluv0zgTCdp5zceSwkGzEDgrrKTfTMUd8P7+oWJvmyMkC8ZMLnpbHGy9uaYNmAEDLEhyA/GqrZSSPGtN3Px6fiesYNbYrJp+iw0NgcSl6pRLqNjF1lxoSKmu4BJfkobr6hg6HOMVaOQGQFB3ck1utAZ9Oq+PZuJa4+n2DB4zGLguG68Tm2j7eSD9FfbhC57a3tzZPxhJPvNN/ecRpUgWlLYe0IrmWqYRzFMzlk2YyZ2Lq6ndWJKWoip1qR7hMjMf02xOjScvIchorcMnUPARiY70rbPLq/HJmnBloye1ud5v/8F3OurspWY3AjxJ6qRM/3/6uiKiqqkS5wWOpiNCNQ0B6QVc56Q9dhWlH7R8Q==
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
