---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    telegram-token: AgAnGNlLjS4VvTrHBggS/2rhvTtJSOVChK7oEXEHA9PRupq+nhWWNCBTkzWzMuIlkOxlyE6gaj9XnCHTOKIhMF4iXgCDWvkDuukw90jXGVJ+wCXpt6Q8UBIqBdH4uo244CPBQPxcWEJn8yXajos4VSD5GKYEi0sDgMIdjAynBOvRrpoqME9FG7/tvrNGX+RUMz6MAhBR1PzOERsnYhYB8H8cdUflBBpAzn2Uw+zINxOc+biCAoJk+pYWjoom6njQOdr4covfAmAxcOZJpaRr9RsclDst/iMKOboZOndmAyr52Tv9J4dpXX3E/WYwuqy/NX6DQvEoAfHog1N1Wwc2Ka+CoYT+fU8uG/A+l6tyxWC2MrL5+Nk1794SFGI9fYWn6cal3E+A6MJC8tK4hS6MZyCUYvR80AlYKY4sh+EDvNJCVwg4uJ1tI4uEylEdnHNjYHpsoQwGVCqk1JADjhxpvhac4fujAaOdlcH9HFTb++XJZE6PJcmy23usU+Wz8soJnS5p5H986m8QuvMur5NMw6X9bIiRrbsJySs9blhS/UB+E77gDb+9OHZx6RTWzt+TqhH3gvcX14J8hwOyNI8slAovyDUdT8sixw6Er3zMEFCPmlU24XmuiEmk9jOq0X5HAv/NzxdM98IjUz/16XvCLeWQg3nJ6tTYkfDnZWdXoDGRIlPUxtJkm/vM5awma5RBQuJSdYxazaW5E9wkEr8fdBN90asFwGFCi7FERfsVAhsPOtZVEVrBJzFMu4GW0qRL
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
