apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    admin.password: AgAGmZx8sylSxufxYCNDLeo9Ph8ZYCAgaI4VXB231EjbEtHvBvh6D+m9gKp4MYudyJnpdTEdMX9A9zy7MLMkdMxeQFvBGd9E1hV9S5y4/lbntTiS1vgHLv4dV2DSwRqwG0LxVvCZI6Xv0cOmPGXZIoc5veVDK4V812+XV/9+WFV6ce9+wCr4EGgEKIUvxA5UE8PXdVTQMH9P1vGr6Rv19QOdV4vm1Z1ycXXjonGQEG5CmJIg7xXKYOfVV51Z8XXUrFS8xrJjGxMre3aagrAyVvP/xeUeYmNW66ltvsQTdqwmglY5FjNM+Z5Zv3EqJA5uOJkVAj6GL6IrfCl0511apF3FJ39+noFYT+xy/gcD4NXeYYU19CVmJEW5i8MKgTE1DnlweOHw+NsSqcD3u8gpbkpMf5ah4ZLhzrdsyxsBf8UqLiDUWYhHD4SNXz1oF5hMucmyqaqmSs64z3jo1+P17eygqjDjRWlgiLWQuwWY12cNGOWRQFkVhjbq1MoYlceOoSP3Z6I4O+5tIF0aAiqKRHjiBAZdeKknN2OiBEDXoYJH1MAFSnkwuJ91XeMMuMXmBgqooZyTocaAp7kjw42vaKLzl56GVgQ+lRkdMntbnU/LcSn7S13B1u0ikcmd9u7WS5yGu4h8tAR5YMG4rR3Cmw3D0nRi90auuqEDYFD1CfyrZFxPjOB8wNR5saHd9KhoAtVfYN0CbrPD8mju62FHxxKUpI0f3XwWw4156eI3OzMClYbQh75Nhvn3l6QaEUPjFbpy+uJLx/Lrx5+83fE=
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
