apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
data:
  context: |
    argocdUrl: https://argocd.dubrovskih.ru
  service.webhook.telegram-direct: |
    url: https://api.telegram.org/bot$telegram-token/sendMessage
    headers:
      - name: Content-Type
        value: application/json
  template.app-deployed: |
    webhook:
      telegram-direct:
        method: POST
        body: |
          {{- $rev := or .app.status.operationState.syncResult.revision .app.status.sync.revision -}}
          {{- $commitMessage := "n/a" -}}
          {{- if and .app.spec.source (not .app.spec.source.chart) -}}
          {{- $meta := call .repo.GetCommitMetadata $rev -}}
          {{- $commitMessage = call .strings.ReplaceAll (call .strings.ReplaceAll $meta.Message "\r" "") "\n" " | " -}}
          {{- end -}}
          {
            "chat_id": "659782773",
            "text": {{ printf "%q" (print "🚀 DEPLOYED in ArgoCD\nApp: " .app.metadata.name "\nRevision: " $rev "\nCommit: " $commitMessage "\nNamespace: " .app.spec.destination.namespace "\nFinished: " .app.status.operationState.finishedAt "\nURL: " .context.argocdUrl "/applications/" .app.metadata.name) }},
            "disable_web_page_preview": true
          }
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per deployed revision.
      oncePer: app.status?.operationState.syncResult.revision
      when: app.status?.operationState?.phase in ['Succeeded'] and app.status.sync.status == 'Synced' and app.status.health.status == 'Healthy'
      send:
        - app-deployed
