apiVersion: v1
kind: Service
metadata:
  name: wyoming-openwakeword
  namespace: wyoming
  labels:
    app.kubernetes.io/name: wyoming-openwakeword
    app.kubernetes.io/component: wake-word
spec:
  type: ClusterIP
  ports:
    - name: wyoming
      port: 10400
      targetPort: 10400
      protocol: TCP
  selector:
    app.kubernetes.io/name: wyoming-openwakeword
