apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-piper-cache
  namespace: wyoming
  labels:
    app.kubernetes.io/name: wyoming-piper
    app.kubernetes.io/component: tts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
