apiVersion: v1
kind: Service
metadata:
  name: wyoming-piper
  namespace: wyoming
  labels:
    app.kubernetes.io/name: wyoming-piper
    app.kubernetes.io/component: tts
spec:
  type: ClusterIP
  ports:
    - name: wyoming
      port: 10200
      targetPort: 10200
      protocol: TCP
  selector:
    app.kubernetes.io/name: wyoming-piper
