apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  namespace: wyoming
  labels:
    app.kubernetes.io/name: wyoming-whisper
    app.kubernetes.io/component: stt
spec:
  type: ClusterIP
  ports:
    - name: wyoming
      port: 10300
      targetPort: 10300
      protocol: TCP
  selector:
    app.kubernetes.io/name: wyoming-whisper
