apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: search
  namespace: dialogue-insights
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: postgres
  name: search
  owner: search
  ensure: present
  databaseReclaimPolicy: retain
