apiVersion: batch/v1
kind: CronJob
metadata:
  name: restore-services
  namespace: power-management
spec:
  schedule: "5 10 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: power-manager
          nodeSelector:
            kubernetes.io/hostname: raspberrypi
          containers:
          - name: restore
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Starting restore at $(date)"

              # Подождать пока jaennil-pc станет Ready
              echo "Waiting for jaennil-pc to be Ready..."
              TIMEOUT=300
              ELAPSED=0
              while ! kubectl get node jaennil-pc 2>/dev/null | grep -q " Ready"; do
                if [ $ELAPSED -ge $TIMEOUT ]; then
                  echo "Timeout waiting for jaennil-pc"
                  exit 1
                fi
                echo "Waiting... ($ELAPSED/$TIMEOUT sec)"
                sleep 10
                ELAPSED=$((ELAPSED + 10))
              done

              echo "jaennil-pc is Ready!"

              # Uncordon
              echo "Uncordoning jaennil-pc..."
              kubectl uncordon jaennil-pc

              # ArgoCD автоматически восстановит replicas через selfHeal
              echo "ArgoCD will restore replicas automatically"

              echo "Restore complete at $(date)"
          restartPolicy: OnFailure
