---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unleash-postgres-credentials
  namespace: unleash
spec:
  encryptedData:
    password: AgAHl/CilTlXH5wdRlM2yJ7YjQi9m2g/bNmmqTo5uAYUmjeiZBUSEj4A1KOFXS13mHDLCGFUUHzOPXwa1lvafsiNupciYwsKFNPzXMjLbXFnq1fRqo3BakJ0MGreRZx10xtmTjnseJQxBmZ0OKIJwd/D7xuMzqHgEB2F4JGX/+e7SO8esME7nUBjyCXDKFHCGkoCcRILgDo+iYKaTHQiXS1bEhRNHLSNV54SrYCS6eUs5auYTk+PwX6eo4pDH2FMUAAK3QtIWfK3jjz7nwAOb6VNZDI1f9pMPK/6dOvMoX41WALFlxaUG+NoKbNpEiB2P7pV9pW/UftymPNMamlgx9MKwsfrEAhwQNXWRWa+MDc1QpmQnwYjxrZPJPbKxc0pc7yt5EZlmr8uq1fQ706WCd4qAruvSWJA9FOFNcP1dpeyZstl+YwGQywK4Ym36L0medortF0efAZtJS9cWI9s6KO8tf4NpbDQzs+k7YCrVb0hxNQOOj6L7iSByOxS4e+0yKlvVzMjhwOkw5rQxEQ5WXV5D6F+bZb93NpouaZ2ikbQNM7W39dhm2/cRXXaSiifN97Gaw/irejcwtjtx7twhAFr1jJQS49TxtokC9zipfsuz2vdVQYBxepBRiVaIsN/E+UjKkEICQyrHaV0DQcQ3ZveHaImoxa4hPqVR+vpRKpiKvHMhpjMjhU5QtAJ32IthSSCHE1Iq8TzBWYOLm7CIwZLQvASDB/nW1o=
    username: AgCU/9bteTb2dmGgz0L8hMpU9K9zWX5nQuc+vyJ4DJJklUhn64rvDFJVYbJSQ1GI1+NH322UE4Xs9dUtOcj89lCU1DmTy79qv5sVA89XrcUwJHWFwyjQOqFxMujDScsiwH9p62rTc8jNnovxMCvLOh4AjDTBp4ql3WnGEhVtgVIdArTBVfWM82XZ+FooCXbWsk+fsANOoczk0BJNo3EvbhLWGvMR22HQt0R4edeiPRocKEiYOZSzARYryNaEJ7FUqG9FwiXtqPuFi3Op/I2fPXxSNMo0MDg1W+XvAqWzu7F8PcpcNeCAM1b4rA8n6DfNf91yjZgIVcUqMYZKR0D0JupFgl3WK7TDx9eHlovQN0/UZ13B54rgL3qjrl591W4ieZt2PeXEvqwWe/TSPg9ZyAPAVmBFq4FqILCN67NkcdX81vtVIT+Z6LHnS9xEBjA93MFmZC3CAPovtanPKXb1Tk73m4cC3IacZ6meH1rc6Zh8VphwSSjfCwxWs/NWUEUkju1n/KdXZKqZRIHnLXVGe3wWWV9FAdtiP/dlfpvh0VniiEaw7v6f2n/cP1dmUvx8aT7IcG7Q3TF+Bf2TVZBVO8rn9nqPtuH3DK1J7SD699e38tbgJ/IKYfLhZFx25tgC69PVNz2cv9K2g/tdaUTQzkTNEw5kH13ZFyjy05GJHmb+X4enFBAl9x0C0igIbxUbrHdFHWX7VW+5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unleash-postgres-credentials
      namespace: unleash
    type: kubernetes.io/basic-auth
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unleash-credentials
  namespace: unleash
spec:
  encryptedData:
    admin-api-token: AgAqQzIAUoVqSRxSeV/Sd/ORQ/G+hSyblDefdcOOcmRJQyR8cOcJ6BfFHhx0kyhn8GNUf58zAbaDZj3Ihmwh3bv8sZNTN3yibYCiwexL8S0uatF/PPAXxccZEYU6fMUy7WSkO3pWfDMjlQP/G3acDSPq8onfAQI40nNZypvdBrqK0F3X9BINR9QZ+upsB2kDRjqwtcaNi6h5PVwdVWCQnqjBWIKtcz80hcyXlp+MwYH52P3dYafnOLJfSqLrobDnS1eXg36wgorSlz60fBgmPgDVwmUXBzdVfvFjp2EBVpRseFqJcS2t3P2DvsMyDA8N0CIkVDrQ/6kNS1SKK5LX3JQ15VZWYomezknFFAh7Pv8MtTIgjOOIggi6XUKFi+QYxioGM8uhgViWLG+TEQbmzzVmHptGG71oPYaHoWtzQdIQyYM3t1Xkc1wP6GV+89WeJ90kN+Q452ykU6Sz7sJ8KiotoR3dpwdMoNCfIsjreSzz/dY9ihfaISun6hxcdA/7ALxvhc7ia+B9DeHpY2oNnPCbpxuTIfX5Vl4Pqxjf2LytBiWKco/eDh0f/R+oBhEcwSmREhcuiiq67OIn5wYZ9PEAkENpKHMOzvQ9Mt2GjcNjpxjShDJ7ztihN2Gxf8rIvBV/ierwzoYk0oWbHsQWe9jxngVfXZ69C/7Ub2ZsjcyIrzXD5euDPza36pglM9q682hGXZYggY1Wa1a0kS0RMxp4h7Tjee0AdvTvrNYOjViY47pYwi4LhAI/56QWQWOpTLNEOvv5JW+pPknzM+P2pDN02duLJDtCmy1JFaJp03bBVnvvtA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unleash-credentials
      namespace: unleash
