---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unleash-postgres-credentials
  namespace: unleash
spec:
  encryptedData:
    password: AgAHl/CilTlXH5wdRlM2yJ7YjQi9m2g/bNmmqTo5uAYUmjeiZBUSEj4A1KOFXS13mHDLCGFUUHzOPXwa1lvafsiNupciYwsKFNPzXMjLbXFnq1fRqo3BakJ0MGreRZx10xtmTjnseJQxBmZ0OKIJwd/D7xuMzqHgEB2F4JGX/+e7SO8esME7nUBjyCXDKFHCGkoCcRILgDo+iYKaTHQiXS1bEhRNHLSNV54SrYCS6eUs5auYTk+PwX6eo4pDH2FMUAAK3QtIWfK3jjz7nwAOb6VNZDI1f9pMPK/6dOvMoX41WALFlxaUG+NoKbNpEiB2P7pV9pW/UftymPNMamlgx9MKwsfrEAhwQNXWRWa+MDc1QpmQnwYjxrZPJPbKxc0pc7yt5EZlmr8uq1fQ706WCd4qAruvSWJA9FOFNcP1dpeyZstl+YwGQywK4Ym36L0medortF0efAZtJS9cWI9s6KO8tf4NpbDQzs+k7YCrVb0hxNQOOj6L7iSByOxS4e+0yKlvVzMjhwOkw5rQxEQ5WXV5D6F+bZb93NpouaZ2ikbQNM7W39dhm2/cRXXaSiifN97Gaw/irejcwtjtx7twhAFr1jJQS49TxtokC9zipfsuz2vdVQYBxepBRiVaIsN/E+UjKkEICQyrHaV0DQcQ3ZveHaImoxa4hPqVR+vpRKpiKvHMhpjMjhU5QtAJ32IthSSCHE1Iq8TzBWYOLm7CIwZLQvASDB/nW1o=
    username: AgCU/9bteTb2dmGgz0L8hMpU9K9zWX5nQuc+vyJ4DJJklUhn64rvDFJVYbJSQ1GI1+NH322UE4Xs9dUtOcj89lCU1DmTy79qv5sVA89XrcUwJHWFwyjQOqFxMujDScsiwH9p62rTc8jNnovxMCvLOh4AjDTBp4ql3WnGEhVtgVIdArTBVfWM82XZ+FooCXbWsk+fsANOoczk0BJNo3EvbhLWGvMR22HQt0R4edeiPRocKEiYOZSzARYryNaEJ7FUqG9FwiXtqPuFi3Op/I2fPXxSNMo0MDg1W+XvAqWzu7F8PcpcNeCAM1b4rA8n6DfNf91yjZgIVcUqMYZKR0D0JupFgl3WK7TDx9eHlovQN0/UZ13B54rgL3qjrl591W4ieZt2PeXEvqwWe/TSPg9ZyAPAVmBFq4FqILCN67NkcdX81vtVIT+Z6LHnS9xEBjA93MFmZC3CAPovtanPKXb1Tk73m4cC3IacZ6meH1rc6Zh8VphwSSjfCwxWs/NWUEUkju1n/KdXZKqZRIHnLXVGe3wWWV9FAdtiP/dlfpvh0VniiEaw7v6f2n/cP1dmUvx8aT7IcG7Q3TF+Bf2TVZBVO8rn9nqPtuH3DK1J7SD699e38tbgJ/IKYfLhZFx25tgC69PVNz2cv9K2g/tdaUTQzkTNEw5kH13ZFyjy05GJHmb+X4enFBAl9x0C0igIbxUbrHdFHWX7VW+5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unleash-postgres-credentials
      namespace: unleash
    type: kubernetes.io/basic-auth
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unleash-credentials
  namespace: unleash
spec:
  encryptedData:
    admin-api-token: AgC+bnxeD5PrZgQz+hYm6FkD/qprR84Zwq9+q4CHHxvaEVZ9Aoo63mwLvXXT8zAYyiJDWM45dZkU6zFOm0wB65yDMOQ9YDL49DPGdy4s1ql2E40D3sHyvwQKVxAjVFS0f1uF+rh61/6BIzAIfSfY8TckoWJP/lsYi9F9ymsfLLG9cNdibGXP7uXvTD4S5ZGNLwWEB0rk9YyGqZRcjxxCu0GZ7BPm2FK12BJUl5Wp0XO4UlVzZDf+md/8G6fz4dBsEqGxj3V9chFs530UYi8Kz8DHFnKHuupsNQ2/LyhFQi2TL2z/FWdG3l1IrOMp1O5+j66G12135U/JIEl0EAr8aNZMbr91IZz2xvTnPBgAMoi0O0Ug+VBhOYtxVCCeKFfMiP2Fimv60vqxJa0A46Ej7Q7Q1dqKqZT6KkENf2L3tXCXC7ARpYzROQbwj7eCgxqN8yw3FYV6Cg8VX6ekA7t/f8ePQUjg/1olL/hFAOOI95+WwFXHqAyaPXohoUFCQXkQW/se7PmtT+PnGlc//B5eKxlcL039iEiu0NpxtBDk8Sgq6V/zlU3dH9IOjK2Tgw8YhuKfqbGW9sdLsNSWQqikxLIbrTu2ETMVZhe19JMBEmfZo9yRFH8/hvHvLqtpoRyrpe0F4Rp9633eqqW36rlhUHhmpFi36n8nX6xdad+uvOCeOiDhnpKql+84SLoEsoacSHzziQoR5j3YhuZBOMgKl/QAGMfNR3bw5IIJS85HvPH7c5GqW1VktqvaVvq7seZNoZEVwB7cWa9pNn4EGVaEdr/h6GqpJg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unleash-credentials
      namespace: unleash
