apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-failover
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:jaennil/homelab-infra
    targetRevision: HEAD
    path: coredns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
