---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaennil/homelab-infra
    targetRevision: main
    path: headscale
  destination:
    server: https://kubernetes.default.svc
    namespace: headscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
