apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      skipCrds: false
      values: |
        defaultSettings:
          defaultReplicaCount: 2
          defaultDataPath: /var/lib/longhorn
          storageReservedPercentageForDefaultDisk: 10
          nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
          replicaAutoBalance: best-effort
        persistence:
          defaultClassReplicaCount: 2
        preUpgradeChecker:
          jobEnabled: false
        metrics:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
