---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sish
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaennil/homelab-infra
    targetRevision: main
    path: sish
  destination:
    server: https://kubernetes.default.svc
    namespace: sish
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
