apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sticker-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaennil/quick-stickers-tg-bot
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sticker-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
