apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webdav
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaennil/homelab-infra
    targetRevision: main
    path: webdav
  destination:
    server: https://kubernetes.default.svc
    namespace: webdav
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
