---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: photoprism-credentials
  namespace: photoprism
spec:
  encryptedData:
    password: AgAfyVqYd2f27AYaHFkZMRFk9NkNxP8qvKMcq7dfKDn6so9sZbqT0T4Vpj1xBntVqp14+AvYA4wSQgRW2mtSlBfk+4uyQ1TSkKW6FvZaXPXVAKVgqf793P8CLi0T032vmqyK9VRXknLh7tMTYwVeBl7pjvR2iz4QxIpw867gIZK4kgyYUV104H+6paLyQZILhK2x1d38pAqPKKtn387Ro8bKnlSLtJP+Q8Tym/BnqaJu7JzPTiqtw8K+AbEWmTSzJnW2Kj8Fl25kWCvNuzx+q8jW5ylom4Vbz+DHAKEr4bAyXj9TXbZ2ikDJQE8EGdw8og3QS46nmRJhiqElWRaXUiQnOovmzDJdhG1fSUU6js/Z1nsWXMQfspJxhTRz1XaRKFpSdHfYw7YtFNAd2Nj0mCPfS9rDxVX02RcrDs5WZvQ22s1ixkuyBoGIS2oLucuObMPAWsycPSAloGfpGA6hy421xvMRClY+N4XxGPPZYYAUh6m5fV2dZDCxr5Gz7e2M/gSEcAxVnWfQK9PVRrp2xZvUP9rCuDDgtndaT3BAhumBwdPCTzvtTaxFnuB9rljT8MwEtDGhXkzwdBCiHXEcc9CmAHJnOYYRHGlCw7O+uCCbjvLH4hM3KJ/7lgs1rH9wuZzgYwk7j48w+DOxWTZ8Yfc/34AYY1kmsX4oj0FI+YE6/SRzNzXAAuq7N4vXyJuxrwStFwphZ09CaRz9
    username: AgCVh2k+LjsKT4Rds/qyKbik5W+vbekZ99Y517HDof+b6FEAx3lG7mIpc3V8AryxwfNN9hmcFUgx3+1M5HBe+kNhUZcVER2GEEnnvZTP9DibbD/9B+JP8eLdp7f/Z/9Y3aKva/K2Nki4t3XLY04H2s0spJtUCYeNvQKVDpBZUGbFeqeKb3HBZR7R64yDpP42I5SbjpxVR+24z3pyTaK9+8lrsX4ZRLAVWdaPTks9mZSeP6Nh0bwvz82KdnytuGpC4zV1UtNsmdY1nlAspjSgOSYKbGEMN1FS+NcWuLICxDtiqsphBxXkXQvvlNPCpUTZxXPG1AAzDPvgIwZfX/cZkVloFj8sEr2qgWIVJzLytElW0FudZ3URxn3a58oRoLA50NNLhSTcCLYXJILlIJuiNiKaCl9yfjWLPC9sR5Gi4/kebvLbP1vLPJJj0msc/N+Fk6rYFzkgqYv/OkH2VdFFpy74zh9hssG3GHu8F3qPn4Pzd3/bKq4SeKkSa0hNfWlwKkCw8UkduvkBD+eiY5P9buFKToVw43lzu5kZhdEbWKYKycoa5bqZQ7TvgbQQ/6ATeteq4DOuf7dasTlPALeIS3osdpKEkAq49TF0bFY3ZLH1JZnVMMnbVZlFhTzClE1tJLYP1F/Hz5JjSCf/UJEVGexLx93emj0hEnWgXRl0AtfFSIQvlbHc6o+YgdAmplAOgoGK/1zIjQ==
  template:
    metadata:
      name: photoprism-credentials
      namespace: photoprism
    type: Opaque
